### ISSUE TITLE
BT interpretation demo

### ISSUE THREAD

**Issue by stineb** [geco-bern/rsofun#113]
This is linked to #98

With model objects returned from `calib_sofun()`, diagnostics of the calibration can be analysed. It would be super nice to have a vignette where the convergence is be visualised and other common metrics, like in [the one for the r3PG model by Vova](https://cran.r-project.org/web/packages/r3PG/vignettes/r3PG-ReferenceManual.html). 

This is not urgent but we should demo what the value of doing a Bayesian calibration is. This should be scheduled to be completed before the accompanying paper is submitted.

**Comment by pepaaran** [comment]
For now I've linked the blogpost by Florian Hartig where I learned how to interpret the results of runMCMC https://florianhartig.github.io/BayesianTools/articles/BayesianTools.html

**Comment by khufkens** [comment]
Fixed as per https://geco-bern.github.io/rsofun/articles/sensitivity_analysis.html in version 4.4
