### ISSUE TITLE
Add acronym to docs

### ISSUE THREAD

**Issue by khufkens** [geco-bern/rsofun#116]
SOFUN: Seasonal Optimisation of Fixation and Uptake of Nitrogen

**Comment by stineb** [comment]
yes, that's the one I had in mind when I first started working on it. But in the meantime, the purpose has deviated and has become much more encompassing. 

I'm thinking more in the direction of 

Simulating Optimal Functioning ...

... but what could be the last two letters?

**Comment by khufkens** [comment]
We can rename the whole thing to better reflect the current state. The repo would redirect. If there is any time to do it, it would be now.

**Comment by khufkens** [comment]
R Simulating Optimal FUNctioning (rsofun), keeping as is... ship has sailed anyway

**Comment by stineb** [comment]
I like Koen's suggestion.
