### ISSUE TITLE
p_model_validation is a "grouped data frame"

### ISSUE THREAD

**Issue by pepaaran** [geco-bern/rsofun#129]
The example `p_model_validation` data is a grouped tibble, which makes it harder to work with because some functions (like `add_row` don't work on grouped tibbles. Is there a reason for having this structure or is it a bug that should be corrected?
@stineb @khufkens

**Comment by khufkens** [comment]
I think the default should be ungrouped - artifact of {tidyverse} not ungrouping by default.
