### ISSUE TITLE
Documentation improvements for BiomeE

### ISSUE THREAD

**Issue by pepaaran** [geco-bern/rsofun#130]
Here I just list some possible improvements for the BiomeE implementation:
- Set `nyeartrend` and `firstyeartrend` to match the available forcing data. Potentially, also `n`, `n_day` and `n_year`, which are passed to the Fortran routine.
- In the "BiomeE usage" vignette, describe how the drivers for Leuning and P-model approaches differ (e.g. time scale, `params_siml$method_photosynth`...). This information is lacking.
- In `run_biomee_f_bysite.R` there should be a check for correct model parameters and simulation dates. Currently it only checks whether forcing variables exist. Parameter-data matching should be checked.
- Replicate documentation of functions from P-model, including data and input variables to all functions.

**Comment by marcadella** [comment]
@stineb maybe we should include this before submitting to CRAN?

**Comment by stineb** [comment]
This will have to be done depending on https://github.com/geco-bern/rsofun/issues/228.
I'm not sure I understand the last point.

**Comment by marcadella** [comment]
@stineb Could you give me a sentence explaining the difference between the photosynthesis models in Biomee so that I can add it to the documentation? (Pt 2 above)

**Comment by marcadella** [comment]
No action need, as documentation has already been improved for release 5.0.0
