### ISSUE TITLE
rwsc problem

### ISSUE THREAD

**Issue by jrmodel** [geco-bern/rsofun#131]
The variable df_drivers2 is a grouped data frame, we need to transfer it into tibble.
df_drivers3 <- as_tibble(df_drivers2).
The calib_sofun and runread_pmodel_f only accepts tibble variables as arguments

**Comment by stineb** [comment]
@jrmodel could you explain what objects you are referring to: Where is `df_drivers2` and `df_drivers3` used?

**Comment by jrmodel** [comment]
This idea is from our discussion about "You can do this by simply combining the nested data frames that are provided as arguments for the calib_sofun() function along rows."

Originally, I can‘t calibrate a single parameter set for all sites.  So I need to write a new cost function instead of cost_mae_swbm. 

df_drivers2 is the driver which includes 13 sites data. It is a nested data frame. After our discussion on Tuesday, I found that we need to change it to a Tibble. Then, It can be the arguments for calib_sofun.

I finally found the solution and posted it here.

**Comment by khufkens** [comment]
closing as resolved
