### ISSUE TITLE
Bug:  `soilm_par_b` has no effect on P-model output

### ISSUE THREAD

**Issue by pepaaran** [geco-bern/rsofun#135]
In the sensitivity analysis, parameter `soilm_par_b` does not change at all the P-model output. 

The parameter is used [in the soil moisture stress function](https://github.com/geco-bern/rsofun/blob/d52de0b9ae5eeffb84f56fbad189846b1240169a/src/photosynth_pmodel.mod.f90#L834) as `y0 = (soilm_par_a + soilm_par_b * meanalpha)` but `meanalpha` (AET/PET) is hard coded as 0 in [this function call](https://github.com/geco-bern/rsofun/blob/d52de0b9ae5eeffb84f56fbad189846b1240169a/src/gpp_pmodel.mod.f90#L206) . Hence, the parameter can never affect P-model predictions.

**Comment by stineb** [comment]
As discussed, let's keep it hard-coded at 0 and remove code related to `soilm_par_b`. 
`soilm_par_a` shall remain a calibratable parameter.
