### ISSUE TITLE
CRAN release workflow

### ISSUE THREAD

**Issue by khufkens** [geco-bern/rsofun#145]
## prepare for release:
- [x] Check CRAN issues (if published)
- [x] urlchecker::url_check()
- [x] devtools::check(document = FALSE)
- [x] rhub::check_for_cran()
- [x] Update cran-comments.md for release
- [x] Update / check NEWS.md
- [x] R CMD check --as-cran    (use Build Source Package to create `rsofun_4.4.tar.gz` file)
- [x] git push remaining changes

## Submit to CRAN:
- [x] Update DESCRIPTION file for Title compliance and specifying package maintainer
- [x] devtools::submit_cran()
- [x] Approve email
- [x] Accepted email

**Comment by khufkens** [comment]
Check Title compliance!

**Comment by pepaaran** [comment]
What should the Title comply with? @khufkens

**Comment by khufkens** [comment]
Should be long and descriptive, not repeating the package name or anything close.

> The mandatory ‘Title’ field should give a short description of the package. Some package listings may truncate the title to 65 characters. It should use title case (that is, use capitals for the principal words: tools::toTitleCase can help you with this), not use any markup, not have any continuation lines, and not end in a period (unless part of …). Do not repeat the package name: it is often used prefixed by the name. Refer to other packages and external software in single quotes, and to book titles (and similar) in double quotes. 

from https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#The-DESCRIPTION-file

**Comment by khufkens** [comment]
The P-model and BiomeE Modelling Framework

would be ok

**Comment by stineb** [comment]
Or the abbreviation of rsofun: 
_R Simulating Optimal FUNctioning framework for site-scale simulations of ecosystem processes_
?

**Comment by khufkens** [comment]
Your call @stineb

**Comment by pepaaran** [comment]
Beni's suggestion is to long, so I would use _The P-model and BiomeE modelling framework_ as title and add _Implements the Simulating Optimal FUNctioning framework for site-scale simulations of ecosystem processes, including model calibration._ as description.
