### ISSUE TITLE
p_model_drivers_vcmax25 update

### ISSUE THREAD

**Issue by stineb** [geco-bern/rsofun#166]
This object needs updating. See info for `p_model_drivers`. 

Or can we omit it?

**Comment by khufkens** [comment]
I've no recollection of creating this, the site names are garbage so I'm not sure where this comes from. IMO this can go.

**Comment by khufkens** [comment]
Site names are from an original poor database Atkins et al. 2017.

**Comment by khufkens** [comment]
fixed as per #168
