### ISSUE TITLE
Remove copyright statements ... 

### ISSUE THREAD

**Issue by stineb** [geco-bern/rsofun#180]
...  and revise header comments in Fortran files.

These statements are obsolete or not applicable anymore, and copyright statements are superseded by license of the package.

@stineb

**Comment by khufkens** [comment]
clarified confusion here: https://github.com/geco-bern/rsofun/commit/702b58e96ab74a2101cf04c50b72b2da528bf3ba

I'll be closing this as not a priority right now. References are correct, as you are listed as author. This can be taken up once on CRAN.
