### ISSUE TITLE
rsofun installation 

### ISSUE THREAD

**Issue by Zinny-E** [geco-bern/rsofun#202]
I am trying to install the rsofun package using the methods in the documentation and getting these errors.

Warning in install.packages :
  package ‘rsofun’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at [https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages]
 
 tried the other methods, it says this
Downloading GitHub repo geco-bern/rsofun@HEAD
Error: Failed to install 'rsofun' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

How can i resolve this.

**Comment by lauramarques** [comment]
install.packages("rsofun") will not work because rsofun is not in CRAN at the moment.

If you are using Windows, you might need to install Rtools before (see [here](https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html))
Then, downloading rsofun via GitHub should work.

**Comment by Zinny-E** [comment]
I am using Mac. Should i follow the same steps.

**Comment by stineb** [comment]
I've added information for installing rsofun from source in the README. Check there first and let us know if this resolves your question or not.
