### ISSUE TITLE
phydro: `le` is not equal to `aet`

### ISSUE THREAD

**Issue by fabern** [geco-bern/rsofun#220]
Using Phydro, the water holding capacity is incorrectly taking into account for the output `le`.
This is linked to the correction happening when the bucket is empty:
https://github.com/geco-bern/rsofun/blob/21f4e98a0f49b06eac6e7444ec5b0baf64cdd2bf/src/waterbal_splash.mod.f90#L119-L129

In the above Fortran code, actual transpiration in units of mm (`aet = daet`) are corrected, but not the actual transpiration in units of energy (`le = daet_e`).

With Francesco we suggest to add another line that does the same correction for `daet_e`, too.

- [ ] TODO: What still needs to be considered is, if the correction should be applied to the total evapotranspiration (`daet`) or also the its two constituents: `daet_soil` and `daet_canopy`.

**Comment by fabern** [comment]
Minimum working example (MWE) follows.

**Comment by stineb** [comment]
I think the root problem is somewhere else. `soilmstress` is never below 1.0. I'm looking at it now.

**Comment by stineb** [comment]
Should be resolved now with 21f4e98a0f49b06eac6e7444ec5b0baf64cdd2bf.

**Comment by fabern** [comment]
>     * [ ]  TODO: What still needs to be considered is, if the correction should be applied to the total evapotranspiration (`daet`) or also the its two constituents: `daet_soil` and `daet_canopy`.

See PR #221that makes a suggestion, yet still unsatisfying since daet_canopy can get negative (FR-Pue with WHC of 5mm, see `test-model-runs.R`)

**Comment by fabern** [comment]
This is solved by PR #221.

When AET is reduced due to soil moisture stress, we reduce AET_soil and AET_canopy proportianlly, i.e. maintain the fraction of actual canopy transpiration to total actual  (AET_canopy / AET), thereby asserting that AET == AET_soil + AET_canopy.
