### ISSUE TITLE
Making the Fortran codebase more maintainable

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#224]
I noted the following things that I believe will make it difficult to maintain the codebase in the future:
- Mixing of attributes from different models in a same top-level derived type class (ex: `vegn_tile_type`, `cohort_type`). Instead, attributes that are specific to a certain model should be grouped in one derived type which can be added to the top-level type as one attribute. Separation of concerns in important!
- Mixing of attributes from different time resolutions (ex: `annualGpp`, `dailyGpp`). Instead, it would be much better to group all daily (resp. annual) diagnostics in their own derived type and add a pointer to `cohort_type`. The advantage is that one can discard the old diagnostic data by dropping the pointer and replacing it with a new fresh instance (with appropriate default values). Subroutines such as `Zero_diagnostics`, which are highly undesirable (!!) would then become unnecessary.
- Non initialization of all attributes. Instead any attribute defined in a derived type should be initialized with a sensible default value or a dummy value (ex: -9999, or better: IEEE NaN), if no good default exists. In other words, any attribute defined in `datatypes.mod.f90` and `classdefs.mod.f90` should have a default value.
- A detail, but there is no reason to add `.mod` in the Fortran file names. This extension is used for compiled files and it is a bit confusing to have it in the source files.
- The `analysis` directory should not be committed to master.

**Comment by fabern** [comment]
Thanks @marcadella !
Reading through you suggestions, these seem to be reasonable and actionable suggestions.
There are certainly similar patterns present in the `pmodel` side of the rpository.
Some patterns might be linked to computational efficiency (presumably `Zero_diagnostics`), but I would say maintainable code has now a higher priority than fast code.

We should discuss these soon in a common meeting with @stineb and/or you could independently start a PR and make suggestions how to solve these in the `phydro` branch.

**Comment by stineb** [comment]
Thanks for the suggestions!

> Mixing of attributes from different models in a same top-level derived type class (ex: vegn_tile_type, cohort_type). Instead, attributes that are specific to a certain model should be grouped in one derived type which can be added to the top-level type as one attribute. Separation of concerns in important!

I need more explanation for this. And we should keep in mind that it may come with its own risks to change the structures too fundamentally

> Mixing of attributes from different time resolutions (ex: annualGpp, dailyGpp). Instead, it would be much better to group all daily (resp. annual) diagnostics in their own derived type and add a pointer to cohort_type. The advantage is that one can discard the old diagnostic data by dropping the pointer and replacing it with a new fresh instance (with appropriate default values). Subroutines such as Zero_diagnostics, which are highly undesirable (!!) would then become unnecessary.

This makes a lot of sense, but some risk of introducing problems with pointers?

> Non initialization of all attributes. Instead any attribute defined in a derived type should be initialized with a sensible default value or a dummy value (ex: -9999, or better: IEEE NaN), if no good default exists. In other words, any attribute defined in datatypes.mod.f90 and classdefs.mod.f90 should have a default value.

This seems like high priority and low risk.

> A detail, but there is no reason to add .mod in the Fortran file names. This extension is used for compiled files and it is a bit confusing to have it in the source files.

Makes sense, but could create conflicts with other branches that contain additional module files. I recommend not to do this.

> The analysis directory should not be committed to master.

Having an analysis subdirectory follows the template suggested by Koen: https://github.com/geco-bern/R_proj_template.

**Comment by marcadella** [comment]
Integration tests are definitely a must. Ideally, every Fortran routine should be tested, in addition to more general simulation output checks. After having see the extent of the code, I agree with @stineb that it would be a major endeavor to refactor the code up to better standard. I would not even be able to define a 'good' standard anyways given my limited experience with the language.
Regarding the default initialization, I am not sure any longer that it is a good thing, since setting a default value when defining a variable will store it in the global memory (it is essentially a static variable), which is absolutely not intuitive and in general not what we want.

**Comment by marcadella** [comment]
After discussing this, we reached the conclusion that no major refactoring would take place, but further development of the code (e.g. adding new features) could be accompanied with upgrade of the code to increase homogeneity between models and developer should be proactive in incrementally improving coding standard where they see fit.
Closing this issue for now as no definite action is required.
