### ISSUE TITLE
Side-effects (spillover) from one pmodel run to the other

### ISSUE THREAD

**Issue by fabern** [geco-bern/rsofun#225]
It appears, that runs of the pmodel (or phydro) model have unwanted side-effects, affecting subsequent runs in the same R session.
This might affect biomee as well. (see https://github.com/geco-bern/rsofun/issues/204#issuecomment-2388255745)

MWE is in:
https://github.com/geco-bern/rsofun/blob/d44e3f89140afd452466042468f326524f65f757/tests/testthat/test-model-runs.R#L214-L224

Specifically, here we find `dpsi` and `psi_leaf` to be zero, when running the pmodel. If we run phydro in between (which supposedly sets `dpsi` and `psi_leaf`), and then run again pmodel, we find that `dpsi` and `psi_leaf` have constant values referring to the last time step of the phydro simulation.

**Comment by marcadella** [comment]
I think it should now be fixed: da95557f
I consider the generalized use of module variables (having a global scope) and `save`ed variables (implicitly or not) is dangerous (and they make the code impossible to parallelized should that be of interest). In addition, the use of flags (eg. `use_phydro`) will make the code unmaintainable very soon. Use of object oriented programming supported by Fortran 2003 is highly encouraged.

**Comment by fabern** [comment]
Thanks Mayeul. Yes this fixed it. The tests from https://github.com/geco-bern/rsofun/commit/dff710a5e22228d87fcda094cb93f6bff2e4445c are now passing on my local machine.
