### ISSUE TITLE
p model breaks with phydro branch

### ISSUE THREAD

**Issue by FrancescoGrossi-unimi** [geco-bern/rsofun#226]
Using the p model withou having netrad and ppfd in master branch it works (set netrad and ppfd to NA).
Using p model without netrad in pyhdro branch works
Using p model without ppfd in phydro branch is breaks

**Comment by fabern** [comment]
Thanks Francesco, can you please post here a minimum working example (MWE) that shows the behavior you refer to?
And also include what output it gives you?

Best would be a few lines of code. As little as needed to show that it breaks.
Then we can use this MWE as a test to see if it still breaks on the newest commits and how to fix it.

You can e.g. copy-paste the short code from the test suite: 
https://github.com/geco-bern/rsofun/blob/dff710a5e22228d87fcda094cb93f6bff2e4445c/tests/testthat/test-model-runs.R#L7-L75

**Comment by FrancescoGrossi-unimi** [comment]
```
library(rsofun)
p_model_drivers$params_siml[[1]]$use_phydro = TRUE
p_model_drivers$params_siml[[1]]$use_gs = TRUE
p_model_drivers$forcing[[1]]$netrad <- NA

params_modl <- list(
  kphio              = 0.04998,    # setup ORG in Stocker et al. 2020 GMD  # TODO: or do we need to have 0.0288
  kphio_par_a        = 0.0,     
  kphio_par_b        = 1.0,
  rd_to_vcmax        = 0.014,      # value from Atkin et al. 2015 for C3 herbaceous
  tau_acclim         = 30.0,
  kc_jmax            = 0.41,
  phydro_K_plant     = 5e-17,
  phydro_p50_plant   = -0.46,
  phydro_gamma       = 0.065,
  phydro_b_plant     = 1,
  phydro_alpha       = 0.08,
  bsoil              = 3,
  Ssoil              = 113,
  whc                = 432 
)

out <- runread_pmodel_f(
  p_model_drivers,
  params_modl
  )
out$data[[1]]

p_model_drivers$forcing[[1]]$ppfd<- NA

out <- runread_pmodel_f(
  p_model_drivers,
  params_modl
  )
out$data[[1]]
```

**Comment by stineb** [comment]
This has low priority to be solved. We don't currently work with setups where PPFD is not given.

**Comment by marcadella** [comment]
@fabern can this be closed?
