### ISSUE TITLE
Homogenize forcing between `run_biomee_f_bysite()` and `run_pmodel_f_bysite()`

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#228]
Homogenizing p-model and biomeE forcing.

**Note:** The scope of this issue is limited to the forcing.

`Remove` in the list below means that the variable should be removed in the forcing data and/or the internal logic (`forcing_siterun_biomee`).

- [x] Remove`rh` (generate from `vpd` in `forcing_siterun_biomee`)
- [x] Remove `temp_soil` (generate from `temp` using `soiltemp_sitch`)
- [x] Remove `year`
- [x] Remove `doy`
- [x] Remove `hour` ~and convert `date` to `date-time` (?)~
- [x] Remove `par` (?) Check who of `PAR` or `radiation` is `ppfd` (the units written in comments are most likely wrong)
- [x] Remove `swc`
- [x] Remove `soilwater`
- [x] ~Add `wind` to p-model (cf: phydro branch), specify that it is currently not used.~
- [x] Update `generate_biomee_driver_data`.
- [x] Update all the data `data/biomee_xxx.rda` files.
  - [x] Keep code snippets that generated those based on FluxDataKit either in `rsofun` or in `FDK` (see https://github.com/geco-bern/rsofun/issues/232)
- [x] Centralize driver info (ex: units). CUrrently it sits in `run_biomee_f_bysite` but it is not obvious for the user where to find it.
  - [x] `data_format.Rmd`  should link to the data definition 

## Summary

- `steps_per_day` parameter added to `paramstype_siml` for biomee.
- Here is what the forcing will look like (with p-model and p-hydro added as reference):

| BiomeE             | p-model         | p-hydro                  |
| ------------------ | --------------- | ---------------          |
| ppfd               | ppfd            | ppfd                     |
| temp              | temp    | temp             |
|                    | tmin   | tmin            |
|                    | tmax    | tmax             |
| rh => vpd                | vpd             | vpd                      |
| prec => rain               | rain            | rain                     |
| wind     | wind (unused)   | wind                     |
| patm              | patm  | patm             |
| co2              | co2      | co2               |
|                    | date            | date                     |
|                    | netrad| netrad      |
|                    | snow            | snow                     |
|                    | fapar           | fapar                    |
|                    |                 | **forcing_acclim**       |
|                    |                 | ...                      |
|                    |                 | **forcing_daytime_mean** |
|                    |                 | ... (needed?)            |
|                    |                 | **forcing_halfhourly**   |
|                    |                 | ... (needed?)            |

**Comment by marcadella** [comment]
I think the contentious points are:
- `PAR`: I think it is not needed as the only usage in the code is `if (cc%status == LEAF_ON .and. forcing%PAR > 0.0) then`, but since `PAR` is always positive it is not a helpful check. In addition, one could use `ppfd` instead.
- `hour` is not used in the code, but if we remove it, there are 24 rows with the same date and without any way to identify them anymore. Maybe this is ok, but it hfeels a bit odd.
- `wind` does not exist for p-model in the main branch. Should I look in another branch?
@stineb @lauramarques

**Comment by fabern** [comment]
Thanks @marcadella for summarizing this.

- `wind` (avg daily windspeed) is used to compute the atmospheric water demand. It influences how much water is lost by transpiration. **This should be kept as input parameter.** For the pmodel, it reappears in the phydro branch [1,2,3 and other places]. Note that currently it is hardcoded to 3 m/s for some calculations [1]. 
- `hour`, from what I understand both models need daily meteorologic input forcing. Where are the 24 rows generated? For pmodel hourly data can be needed to compute the acclimation of the leaves to e.g. the 3hr-average over noon for the temperature, but I believe Jaideep handled this in the phydro branch by computing this previously and adding a new input `forcing_acclim` [4].
- `PAR` (photosynthetically active radiation) is that part of the sunlight that can be used for photosynthesis. Not sure (haven't checked) but it might be recomputed as a fixed fraction of the total sunlight somewhere in the code? Or could it be linked to the fAPAR input?

[1] https://github.com/geco-bern/rsofun/blob/b6ab2d43e13daf446f63c933fc1234f3acbcb56f/src/gpp_pmodel.mod.f90#L248
[2] https://github.com/geco-bern/rsofun/blob/b6ab2d43e13daf446f63c933fc1234f3acbcb56f/src/photosynth_phydro.mod.f90#L29
[3] https://github.com/geco-bern/rsofun/blob/b6ab2d43e13daf446f63c933fc1234f3acbcb56f/src/waterbal_splash.mod.f90#L574
[4] https://github.com/geco-bern/rsofun/blob/b6ab2d43e13daf446f63c933fc1234f3acbcb56f/vignettes/pmodel_use.Rmd#L428-L429

**Comment by fabern** [comment]
- `vpd`: I would rather argue to keep vapour pressure deficit as input instead of relative humidity. Since this is more widespread in the photosynthesis literature.
- `swc` and `soilwater` are related and at least in p-model are important variables controlling how much water plants transpire. It is possible that they are not computed as state variables in biomee and are thus required as a time-varying forcing. However, if pmodel and biomee are coupled then pmodel would compute this as state variable, so it will not be needed anymore as input forcing. I'm not sure I understand what you suggest in the first post, are you suggesting we should remove them from the input? But currently they are used by biomee, right?

**Comment by marcadella** [comment]
- Ok, so I can add `wind` to p-model in master (and specify that it is currently not used).
- @fabern p-model in master uses daily data, while biomeE uses hourly data.
- `radiation` is used in the code, while `PAR` is only used in this if statement which could be dropped I believe. The weird thing is that the comments say that `radiation` is in `W/m2` (ok), but `PAR` is in `umol/m2/s`. This does not make sense as that is the unit of a PPFD.  Given that `radiation` is not negative during the night in the data, I think it actually is PAR, and PAR is actually PPFD.

**Comment by marcadella** [comment]
After digging a bit more, `radiation` is the SW downwelling radiation. I find it strange that BiomeE does not use PAR at all. Any thought @stineb ?

**Comment by marcadella** [comment]
For sorting the issue with `hod` (hour of day), since it does not exists in p-model and makes sense for biomeE, but is not used, I propose to change the type of the `date` field to `date-time` (`POSIXct`). Doing so makes the models flexible with regards to the time resolution used (i.e. one can go down to half-hourly or even less without having to change the code).

**Comment by stineb** [comment]
Re date-time: I guess the point of separating year, doy (day-of-year), and hod (hour-of-day) in the forcing is because Fortran doesn't offer an easy way to handle date-time objects. 

Indeed, the timestepping and provision of date/time information through the forcing array is handled differently now for the P-model and BiomeE. In P-model, it's assumed to always be daily and the number of (transient) simulation years is determined from the number of rows in the forcing data frame divided by 365. In `run_pmodel_f_bysite.R`:
```r
  firstyeartrend_forcing <- forcing %>%
    dplyr::ungroup() %>%
    dplyr::slice(1) %>%
    dplyr::pull(date) %>%
    format("%Y") %>%
    as.numeric()

  nyeartrend_forcing <- nrow(forcing)/ndayyear
```
But then, the date (time) is not passed to Fortran as part of the forcing.

In BiomeE, because it can handle hourly or daily forcing, it's done more flexibly, but the date and hour have to be passed to Fortran as part of the forcing. This is necessary because (in both BiomeE and P-model), the time steps have a meaning for the C balance and dynamics. They cannot be treated in an entirely generic way. 

Now, we can chose to either do it the P-model way or the BiomeE way. What do you prefer?

Regarding PAR/radiation: this was adopted from the original code and indeed, this is messy. Let's use just PPFD (mol photons m-2 s-1) in the forcing. However, for the gs_leuning photosynthesis routine, shortwave radiation is used (W m-2). PAR is a fraction of SW radiation. And PPFD is PAR expressed in mol photons. They can be interconverted as done in FluxDataKit (`R/fdk_format_drivers.R`)
```r
    # conversion factor from SPLASH: flux to energy conversion,
    # umol/J (Meek et al., 1984)
    kfFEC <- 2.04
...
         # photosynthetic photon flux density based on shortwave radiation
         # convert from J/m2/s to mol/m2/s;
         # kfFEC = 2.04 is the flux-to-energy conversion, micro-mol/J
         # (Meek et al., 1984)
         ppfd = SW_IN_F_MDS * kfFEC * 1.0e-6,
```
And in rsofun `src/gpp_biomee.mod.f90`:
```F90
    real, parameter :: rad_phot = 0.0000046 ! PAR conversion factor of J -> mol of quanta 

    ! Convert Solar influx from W/(m^2s) to mol_of_quanta/(m^2s) PAR,
    ! empirical relationship from McCree is light=rn*0.0000046
    light_top = rad_top*rad_phot;
    par_net   = rad_net*rad_phot;
```
When providing all in PPFD through the forcing, the latter conversion in `src/gpp_biomee.mod.f90` can be avoided.

**Comment by marcadella** [comment]
The `hod` parameter is not used in the code at all, so I can remove it without any need to change anything else.

**Comment by stineb** [comment]
I think `hod` is indeed used. In `sofun_r.f90`:
```F90
    timestep   = real(forcing(2,3)) - real(forcing(1,3))  ! This takes the hour of day (a numeric) from the forcing file
```
Reference by index: column 3 is `hod`. The way the time steps are interpreted in BiomeE could serve as a blueprint also for P-model:
```F90
    !----------------------------------------------------------------
    ! INTERPRET FORCING
    !----------------------------------------------------------------
    timestep   = real(forcing(2,3)) - real(forcing(1,3))  ! This takes the hour of day (a numeric) from the forcing file
    timestep_d = real(forcing(2,2)) - real(forcing(1,2))  ! This takes the day of year (a numeric) from the forcing file
    if (abs(timestep) < eps .and. abs(timestep_d - 1.0) < eps) then
      ! forcing is daily
      timestep = 24.0
    end if
    myinterface%steps_per_day = int(24.0/timestep)
    myinterface%dt_fast_yr = 1.0/(365.0 * myinterface%steps_per_day)
    myinterface%step_seconds = 24.0*3600.0/myinterface%steps_per_day ! seconds_per_year * dt_fast_yr
    ntstepsyear = myinterface%steps_per_day * 365
```

**Comment by marcadella** [comment]
Quick questions: What forcing is used during the spinup years?

**Comment by marcadella** [comment]
Problem: `soiltemp` uses soil info to compute the soil temperature. This info is not included in BiomeE. It is therefore not possible to generate the soil temperatures for air temperatures. Or am I missing something?

**Comment by fabern** [comment]
> Quick questions: What forcing is used during the spinup years?

The first X years (X=`recycle`) are reused so that they add up to the number determined by `spinupyears`.

https://github.com/geco-bern/rsofun/blob/2d8fdedbf4d38a2929b72a42b720a6bc672a039a/src/params_siml_biomee.mod.f90#L173

**Comment by marcadella** [comment]
> > Quick questions: What forcing is used during the spinup years?
> 
> The first X years (X=`recycle`) are reused so that they add up to the number determined by `spinupyears`.
> 
> https://github.com/geco-bern/rsofun/blob/2d8fdedbf4d38a2929b72a42b720a6bc672a039a/src/params_siml_biomee.mod.f90#L173

Thanks

**Comment by marcadella** [comment]
Ok, but I still can't use `soiltemp` to compute the soil temperature since it requires a full blown water balance which is not found in biomee (`wscal` is used).

**Comment by fabern** [comment]
Ok, so given this limitation we might consider to keep `temp_soil` in the input forcing for `biomee` for the moment. 
Let's discuss this Thursday in person.

**Comment by stineb** [comment]
As far as I can see, soil temperature is nowhere used in BiomeE, therefore we also don't need it in the forcing.

**Comment by marcadella** [comment]
@stineb Right now the output of biomee contains RH. Should I convert it to VPD instead?

**Comment by marcadella** [comment]
All implemented and PR'ed.
