### ISSUE TITLE
Leap years

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#231]
Both biomeE and p-model run annual and monthly loops. Aren't leap years causing drift away issues?

**Comment by marcadella** [comment]
It looks like the dates are removed from the data (something I've seen in BiomeE too), then zipped again in the output. This is error prone (as an example, as you mention, I might even be that the inputs do not discard leap days...). In addition, I understand that leap days are removed for sake of simplicity, but plants are not on holidays during leap days ;)
As a more general statement, I think the way the models are run with annual and monthly loops make everything very complicated. Wouldn't it have been easier to have a unique loop generating 'blindly' the predictions running at the same resolution as the forcing (daily or hourly) in fortran, and doing the aggregation (yearly and monthly tile statistics) in R, knowing that each predicted data embeds a timestamp which can be used to easily group yearly/monthly data together. Advantages are:
- Less Fortran code (and much simpler)
- Separation of concerns (prediction vs data aggregation/statistics)
- No issue with leap years (no need to skip them at all)

**Comment by stineb** [comment]
The dynamic time step treatment of BiomeE could be adopted in rsofun. Relevant code in `sofun_r.f90`:
```
    !----------------------------------------------------------------
    ! INTERPRET FORCING
    !----------------------------------------------------------------
    timestep   = real(forcing(2,3)) - real(forcing(1,3))  ! This takes the hour of day (a numeric) from the forcing file
    timestep_d = real(forcing(2,2)) - real(forcing(1,2))  ! This takes the day of year (a numeric) from the forcing file
    if (abs(timestep) < eps .and. abs(timestep_d - 1.0) < eps) then
      ! forcing is daily
      timestep = 24.0
    end if
    myinterface%steps_per_day = int(24.0/timestep)
    myinterface%dt_fast_yr = 1.0/(365.0 * myinterface%steps_per_day)
    myinterface%step_seconds = 24.0*3600.0/myinterface%steps_per_day ! seconds_per_year * dt_fast_yr
    ntstepsyear = myinterface%steps_per_day * 365

    allocate(myinterface%climate(ntstepsyear))
    allocate(myinterface%pco2(ntstepsyear))
```
But you see, it creates the complication that some arrays then have a dynamic size. 

Regarding leap years: Again, this would require dynamic array size definitions. I agree that this has some appeal but comes at the cost of added complexity of the code. 

And we really only introduce a bias through that if we would calibrate the model to annual totals (of a given variable). In that case, we would make a systematic error of 1/(4*365) = 0.07%. Worth the effort? However, we don't calibrate to annual totals.
