### ISSUE TITLE
CN ratio is NaN in vegetation_biomee

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#238]
There is an is an issue in vegetation_biomee (master branch), where both `CNfast` and `CNslow` are both NaN. This comes from : 
- the denominator `vegn%psoil_fs%n%n14` (resp `vegn%psoil_sl%n%n14`) is 0, because:
- when the soil pools are initialized, `psoil_fs%n` (resp. `psoil_sl%n`) are a scaled version of `psoil_fs%c` (resp. `psoil_sl%c`), which is set to 0 in the driver (`init_fast_soil_C=init_slow_soil_C=0`).

**Comment by stineb** [comment]
`CNfast` and `CNslow` are dynamically simulated (and not prescribed), right? In that case, it would make most sense to initialised the soil pools with a small quantity >0. For example, 10 g m-2 for the fast and 1 g m-2 for the slow pool.
