### ISSUE TITLE
`psi_sat_ref` initialized with negative values in `generate_biomee_driver_data`

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#239]
`psi_sat_ref` initialized with negative values in `generate_biomee_driver_data`, which seems odd. But this value does not seem to be used anywhere (other than computing some derived constant soil parameters, which are themselves not being used). Should we remove all of these?

**Comment by stineb** [comment]
Yes, remove them. Psi is a water potential (suction head), which is negative in soil.

**Comment by marcadella** [comment]
Keeping it to avoid touching the water model.
