### ISSUE TITLE
get_steering clean-up

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#240]
Changes in `get_steering` in `params_siml_biomee` by @lauramarques are bypassing `get_cycleyear`. It is unclear if it is the right behavior or if it was a mistake or just a quick hack for testing something. Confirmation of the intended behavior is needed as well as code clean-up in this case.

**Comment by stineb** [comment]
Yes, I don't know what that is about in BiomeE. Ideally, the way it's done for P-model runs is adopted also for BiomeE runs. 

The three parameters `recycle`, `spinupyears`, and `firstyeartrend` determine what simulation year to start the spinup with. The clue is to recycle a certain sequence, say `recycle = 5`. Then, the first 5 years of the forcing are taken and recycled during the spinup such that in the last spinup year, the last year of that sequence is used. Makes sense?

**Comment by marcadella** [comment]
In addition, why would p-model use forcing with different years for CO2 and climate?? (`forcingyear` vs `climateyear`)

**Comment by stineb** [comment]
`firstyeartrend` is set at the level of R. Can also be avoided at R level, but added at Fortran level. But that's not worth the effort IMO.

forcingyear and climateyear distinguished is intentional. you can just adopt as it's done for P-model runs.

**Comment by marcadella** [comment]
Just so we are at the same page: as it is implemented in p-model, a recycle of 3 years looks like this:
- CO2: 2009, 2009, 2009, 2009, ...
- climate: 2009, 2010, 2011, 2009, ... 
Is that really what you want??

**Comment by stineb** [comment]
correct. The purpose recycling a sequence of >1 year of climate data is to have inter-annual variability in the climate and to have this interannual variability to be perfectly stationary. The variability matters for the dynamics and steady-state of the system. therefore it's very different from spining up to a single year repeated N times. CO2 has no interannual variability, just a long-term trend. The spinup assumes that CO2 is constant.
