### ISSUE TITLE
biomee_p_model_output and biomee_gs_leuning_output not properly documented and generated

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#241]
- Both `biomee_p_model_output` and `biomee_gs_leuning_output` are documented as 'Small tests dataset to validate calibration routines' in `Rdata.R`, which looks like a copy paste of the doescription of `biomee_validation`. The format is also wrong.
- Both files should be regenerated from `generate_biomee_driver_data.R`, but are not.

**Comment by marcadella** [comment]
@stineb , can you confirm that:
- both files are example outputs of biomee using the example drivers, 
- they should be generated in `generate_biomee_driver_data.R`,
- their format should be `year, GPP, PlantC`

**Comment by stineb** [comment]
To the three points:

- yes they should be
- wouldn't it make more sense to generate them in something like `data-raw/generate_biomee_output.R`?
- subsetting to only these variables from the annual tile-level output can be done in `data-raw/generate_biomee_output.R`.

**Comment by marcadella** [comment]
Done
