### ISSUE TITLE
`totseed` and `totNewC` contain trash on the first spinup year

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#243]
`totseed` (C and N) and `totNewC` (C and N) are initialized in `vegn_reproduction()` which is called after `annual_diagnostics()` resulting in the first spinup year annual data containing trash for this variables.

**Comment by marcadella** [comment]
@stineb Should I initialize to 0 in `initialize_vegn_tile()`?

**Comment by stineb** [comment]
if they are components of the `vegn` derived type, then yes

**Comment by marcadella** [comment]
Added default initialization for these.
