### ISSUE TITLE
Biomee Density12 has a sawtooth shape

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#245]
Here is a simulation using the biomee_p_model_drivers (with `method_mortality` set to 'dbh').
The periodicity is roughly 52 years, and the collapse in Density12 correspond to minima in GPP. It is basically as if the number of big trees was decreasing down to 0 until exploding up again. Sounds rather odd...

![image](https://github.com/user-attachments/assets/c9cdedd8-7c67-425c-80a7-a8656db75a72)
![image](https://github.com/user-attachments/assets/0b027aa2-2654-4ae3-8962-5e3698a24fab)
![image](https://github.com/user-attachments/assets/65e2906e-0ddf-4c08-bdf5-8601cac1b1cd)

**Comment by fabern** [comment]
Do you see this with and without interventions? Is it a yearly sawtooth?

Interventions would of course lead to discontinuities: e.g. if trees are cut down, the number of trees `Density` and `Density12` are affected.
But even without interventions: natural mortality also reduces the numbers of trees. I believe this is implemented as a reduction that happens once per year. So this could explain a yearly sawtooth pattern...

**Comment by marcadella** [comment]
No disturbances, and it happens every 50 years ish during spinup.

**Comment by marcadella** [comment]
![image](https://github.com/user-attachments/assets/c9cdedd8-7c67-425c-80a7-a8656db75a72)
![image](https://github.com/user-attachments/assets/0b027aa2-2654-4ae3-8962-5e3698a24fab)

**Comment by marcadella** [comment]
- It is normal that there are more smaller trees than bigger one.
- It is also normal that larger trees have a higher mortality rate.
- I also agree that jumps are expected given that trees that are just under 12cm one year will pass the 12cm threshold next year. But the observed jumps are not realistic I think. It could comes from the mortality parameters that are set to 1, which seems like an arbitrary value...

**Comment by stineb** [comment]
It would be useful to understand what happens in the model that causes the large oscillations. That there are oscillations is not per se implausible. But that they are so strong is strange.

**Comment by stineb** [comment]
This should not be treated as an issue since I don't think this points to a code bug, but rather to a (potentially unrealistic) model dynamics. How realistic it is, whether it happens only under certain forcing, etc. remains to be figured out. 

@lauramarques in the D-BEN simulations, it seems BiomeE by Ensheng doesn't have such large oscillations as we do. Any ideas for why this happens in our model version?

**Comment by marcadella** [comment]
Closing this as @fabern is looking at the model behaviors in more details already.
