### ISSUE TITLE
Bug in `mergerank`

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#246]
`mergerank` is recursively calling itself:
```
call mergerank(x,a,na,t)
call mergerank(x,a(na+1),nb,t)
```
The first call is fine, however the second it obiously wrong as `a(na+1)` is a scalar. I assume that what was meant was `call mergerank(x,a(na+1:n),nb,t)`.

I don't quite understand what this function is supposed to do so I let you judge @stineb .

**Comment by stineb** [comment]
Do you have an indication that there is an issue with this? I've never touched that but I have full confidence that it's doing what it ought to. Doesn't it?
