### ISSUE TITLE
Potential carbon leak in biomass

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#250]
The simulations below come from `biomee_p_model_drivers` with `method_mortality` set to 'cstarvation'. GPP, Density (and Density12) indicate a steady-state after the spinup time, however `PlantC` continues increasing almost linearly. Isn't that a carbon leak in the model? How can the biomass keep increasing if the system is in pseudo-steady state?

![image](https://github.com/user-attachments/assets/1a97f862-3987-46db-b741-9e596feb6208)
![image](https://github.com/user-attachments/assets/510b02cb-e26b-4629-b3a4-b8621e5cfd1a)

**Comment by stineb** [comment]
This is experimental, right @lauramarques ? Please add a comment to declare its experimental stage (as for C starvation mortality). Anyways, please keep it as it is interesting and, given we resolve some other, related questions, may be used again in the future.

**Comment by marcadella** [comment]
Unfortunately, a C leakage (or buildup) is unlikely to come from the mortality method, and may indicate a flow somewhere else in the model. I just used this specific method as it is the only one that is currently outputting some meaningful result (see #249 and #245 ).

**Comment by marcadella** [comment]
After discussion it turns out that this model builds up infinitely large trees which explains that the biomass is increasing while the density12 decreases.
