### ISSUE TITLE
Make different example drivers consistent (not across pmodel and biomee, but within each model)

### ISSUE THREAD

**Issue by fabern** [geco-bern/rsofun#257]
We have decided against harmonizing the driver data **across** pmodel and biomee (see https://github.com/geco-bern/rsofun/issues/228).
However, there are currently still differences in the example drivers **within** each model, that I believe we should homogenize. Namely:
  - differences between `biomee_gs_leuning_drivers` and `biomee_p_model_drivers`
  - and differences between `p_model_drivers_vcmax25` and `p_model_drivers`

Here is what I noticed:
- [x] documentation: `?biomee_gs_leuning_drivers` and `?biomee_p_model_drivers` are outdated. They still contain `soil_texture`, but are missing `params_tile`, `params_species`, `params_soil`, `init_cohort`, and `init_soil`
- [x] documentation: also document all columns of the nested data.frames of `?biomee_gs_leuning_drivers` and `?biomee_p_model_drivers` following the structure of the documentation of `?p_model_drivers`
- [x] in `biomee_gs_leuning_drivers` and `biomee_p_model_drivers`: remove `sitename` from the **nested** `site_info` as it breaks `unnest`.
- [ ] ~in `p_model_drivers`: add to `site_info` the columns `year_start` and `year_end`  (Setting `year_start` and `year_end` to what? NA? Are they used?)~
- [ ] ~in `p_model_drivers_vcmax25` and `p_model_drivers`: modify column order of `p_model_drivers_vcmax25$forcing`~

@marcadella, could you please take care of this?

Below code can help in diagnosing and checking if it is now consistent.
```R
# site_info:
rsofun::p_model_drivers$site_info             # is missing year_start, year_end
rsofun::p_model_drivers_vcmax25$site_info     # contain:           lon, lat, elv, year_start, year_end, whc
# rsofun::biomee_gs_leuning_drivers$site_info # contain: sitename, lon, lat, elv, year_start, year_end, classid, c4, whc, koeppen_code, igbp_land_use
# rsofun::biomee_p_model_drivers$site_info    # contain: sitename, lon, lat, elv, year_start, year_end, classid, c4, whc, koeppen_code, igbp_land_use

# Make the following work:
rsofun::biomee_gs_leuning_drivers |> unnest(site_info)
rsofun::biomee_p_model_drivers    |> unnest(site_info)

# params_siml: are okay
# rsofun::p_model_drivers$params_siml
# rsofun::p_model_drivers_vcmax25$params_siml
# rsofun::biomee_gs_leuning_drivers$params_siml
# rsofun::biomee_p_model_drivers$params_siml

# forcing: reorder p_model_drivers_vcmax25
rsofun::p_model_drivers$forcing
rsofun::p_model_drivers_vcmax25$forcing[[1]]  # make order the same as in `rsofun::p_model_drivers$forcing`
# rsofun::biomee_gs_leuning_drivers$forcing
# rsofun::biomee_p_model_drivers$forcing

# # other params: are okay
# rsofun::biomee_gs_leuning_drivers$params_tile[[1]]
# rsofun::biomee_p_model_drivers$params_tile[[1]]
# rsofun::biomee_gs_leuning_drivers$params_species[[1]] |> tibble()
# rsofun::biomee_p_model_drivers$params_species[[1]] |> tibble()
# rsofun::biomee_gs_leuning_drivers$params_soil[[1]]
# rsofun::biomee_p_model_drivers$params_soil[[1]]
# # other init conditions: are okay
# rsofun::biomee_gs_leuning_drivers$init_cohort[[1]]
# rsofun::biomee_p_model_drivers$init_cohort[[1]]
# rsofun::biomee_gs_leuning_drivers$init_soil[[1]]
# rsofun::biomee_p_model_drivers$init_soil[[1]]
```

**Comment by marcadella** [comment]
Won't do pt 3 and 4: I have changed the documentation of `site_info` saying it is a freely usable data structure for documenting a dataset (but must include lat, lon, elv and whc). The reason being that we do not wan't to re-generate the dirvers.

**Comment by marcadella** [comment]
Ah ok, I will fix this one then.

**Comment by marcadella** [comment]
Everything is implemented in update_vignettes branch
