### ISSUE TITLE
Post CRAN submission process

### ISSUE THREAD

**Issue by marcadella** [geco-bern/rsofun#262]
- Release v5.0.0 (SHA: 2bb73153cbbccf1593ecd2e9012c01c64bf5007d)

**Comment by marcadella** [comment]
@fabern It does not look like I have the rights to do a release. Could you do it?

**Comment by fabern** [comment]
You have now status of "maintainer". Does that allow you to make the release?

**Comment by marcadella** [comment]
v5.0 released
